kind: Stream
name: ORDERS
subjects:
  - "orders.*"
storage: file
max_age: 1h
replicas: 1

---
kind: Consumer
name: orders-processor
streamName: ORDERS
durable_name: orders-processor
deliver_policy: all
ack_policy: explicit
max_deliver: 5

---
kind: KeyValue
name: CONFIG_DATA
description: "Application Configurations"
history: 5
ttl: 24h